### ISSUE TITLE
E10s compatible?

### ISSUE THREAD

**Issue by mirh** [brettz9/open-wiki-edit-page#1]
Even better if switched to webextension, so firefox won't ever complain agian

p.s. binaries should go uploaded in "release" section, not put in source control

**Comment by brettz9** [comment]
I prefer to have the XPI file (which is not too large to worry about) in source control as I can be warned of diffs (or lack thereof). But yeah, usually better not to put it in source control.

And yes, this ought to be redone as a webextension. I'm really too busy to maintain this now. Feel free to adapt it if you are so inclined.

**Comment by brettz9** [comment]
I've made the move to webextensions, and I see it is available at [AMO](https://addons.mozilla.org/en-US/firefox/addon/open-wiki-edit-page/).

FWIW, this being now a webextension, it was also easy to make it available to Chrome: https://chrome.google.com/webstore/detail/open-wiki-edit-page/bgkapcgalpheigeojpgjgomopmmdpgaj?hl=en-US .

Unfortunately, as per https://bugzilla.mozilla.org/show_bug.cgi?id=1341804#c2 , webextensions lacks a means to fine-tune whether a context menu applies or not, so the one disadvantage in making the migration is that the context menu must now appear on all links instead of only those matching a pattern. But this move was really necessary to continue support.

And FWIW, I'm now excluding the binary from Git.

Best wishes...

**Comment by brettz9** [comment]
Actually, I've just published a fix (already available on AMO and on the Chrome store) which avoids showing the links except on URLs which match the wiki pattern (and at least for Firefox 60+, not sure when Chrome may be on board with the change, it also won't show the ISBN links for non-ISBN wiki pages and vice versa). 

Thus, I believe the behavior should now be as before (at least it will be once Firefox 60+ is widespread).
